# Generated by Django 4.1.7 on 2023-02-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Résumé', max_length=255),
        ),
    ]
