# Generated by Django 4.1.7 on 2023-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeBlog', '0004_categorie_post_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(max_length=255),
        ),
    ]
