# Generated by Django 4.1.7 on 2023-03-02 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LeBlog', '0005_alter_post_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='resumee', to=settings.AUTH_USER_MODEL),
        ),
    ]
