# Generated by Django 4.1.7 on 2023-03-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeBlog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Clique pour avoir plus de détails.', max_length=255),
        ),
    ]
