# Generated by Django 4.1.7 on 2023-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeBlog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
