# Generated by Django 4.1.7 on 2023-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeBlog', '0010_profile_github_url_profile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='microsoft_teams_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='microsoft_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
