# Generated by Django 4.1.7 on 2023-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeBlog', '0011_remove_profile_microsoft_teams_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='microsoft_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='microsoft_teams_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
